name: Deploy to VPS STAGING

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          cat <<EOF > .env
          PORT=${{ vars.PORT }}
          DBHOST=${{ vars.DBHOST }}
          DBPORT=${{ vars.DBPORT }}
          DBUSER=${{ vars.DBUSER }}
          DBPASS=${{ secrets.DBPASS }}
          DBNAME=${{ vars.DBNAME }}
          RAJAONGKIR_API=${{ secrets.RAJAONGKIR_API }}
          RAJAONGKIR_BASE_URL=${{ vars.RAJAONGKIR_BASE_URL }}
          JWTSECRET=${{ secrets.JWTSECRET }}
          REDISURL=${{ vars.REDISURL }}
          CLOUNINARY_CLOUD_NAME=${{ vars.CLOUNINARY_CLOUD_NAME }}
          CLOUNINARY_API_KEY=${{ secrets.CLOUNINARY_API_KEY }}
          CLOUNINARY_API_SECRET=${{ secrets.CLOUNINARY_API_SECRET }}
          SMTP_HOST=${{ vars.SMTP_HOST }}
          SMTP_PORT=${{ vars.SMTP_PORT }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          SMTP_FROM=${{ vars.SMTP_FROM }}
          SMTP_SECURE=${{ vars.SMTP_SECURE }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF

      - name: Clean previous build
        run: rm -rf dist

      - name: Build project
        run: npm run build
        env:
          PORT: ${{ vars.PORT }}
          DBHOST: ${{ vars.DBHOST }}
          DBPORT: ${{ vars.DBPORT }}
          DBUSER: ${{ vars.DBUSER }}
          DBPASS: ${{ secrets.DBPASS }}
          DBNAME: ${{ vars.DBNAME }}
          RAJAONGKIR_API: ${{ secrets.RAJAONGKIR_API }}
          RAJAONGKIR_BASE_URL: ${{ vars.RAJAONGKIR_BASE_URL }}
          JWTSECRET: ${{ secrets.JWTSECRET }}
          REDISURL: ${{ vars.REDISURL }}
          CLOUNINARY_CLOUD_NAME: ${{ vars.CLOUNINARY_CLOUD_NAME }}
          CLOUNINARY_API_KEY: ${{ secrets.CLOUNINARY_API_KEY }}
          CLOUNINARY_API_SECRET: ${{ secrets.CLOUNINARY_API_SECRET }}
          SMTP_HOST: ${{ vars.SMTP_HOST }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ vars.SMTP_FROM }}
          SMTP_SECURE: ${{ vars.SMTP_SECURE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Prepare SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -v -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null deploy-sf@${{ secrets.SERVER_HOST }} "echo 'SSH connection successful'"

      - name: Debug - Echo server destination
        run: |
          echo "SERVER_DEST: ${{ vars.SERVER_DEST }}"
          echo "DBUSER: ${{ vars.DBUSER }}"
          echo "secrets DBUSER: ${{ secrets.DBUSER }}"
          echo "secrets SERVER_DEST: ${{ secrets.SERVER_DEST }}"
          echo "SERVER_USER: ${{ secrets.SERVER_USER }}"
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"

      - name: Deploy via rsync over SSH
        run: |
          rsync -avz --exclude=node_modules --exclude='*/node_modules/*' -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
            ./dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ vars.SERVER_DEST }}

      - name: Restart PM2 App
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} \
            "cd ${{ vars.SERVER_DEST }} && pm2 restart backend-sf-staging"

      - name: Cleanup
        run: rm -f key.pem
